Repository sinaptik-ai/pandas-ai, pull requests merged in 2024-07, with the labels that each got.

#1260 Add scarf telemetry in pandasai
  pandasai/__init__.py
  pandasai/__version__.py
  pandasai/helpers/logger.py
  pandasai/helpers/query_exec_tracker.py
  pandasai/helpers/telemetry.py
Labels: size:M

#1266 feat(security): add security agent
  docs/advanced-security-agent.mdx
  docs/mint.json
  examples/security_agent.py
  pandasai/agent/agent.py
  pandasai/agent/base.py
  pandasai/agent/base_security.py
  pandasai/ee/agents/advanced_security_agent/__init__.py
  pandasai/ee/agents/advanced_security_agent/pipeline/advanced_security_pipeline.py
  pandasai/ee/agents/advanced_security_agent/pipeline/advanced_security_prompt_generation.py
  pandasai/ee/agents/advanced_security_agent/pipeline/llm_call.py
  pandasai/ee/agents/advanced_security_agent/prompts/advanced_security_agent_prompt.py
  pandasai/ee/agents/advanced_security_agent/prompts/templates/advanced_security_agent_prompt.tmpl
  pandasai/pipelines/chat/code_cleaning.py
  tests/unit_tests/agent/test_agent.py
  tests/unit_tests/ee/security_agent/test_security_agent.py
  tests/unit_tests/ee/security_agent/test_security_llm_call.py
  tests/unit_tests/ee/security_agent/test_security_prompt_gen.py
  tests/unit_tests/pipelines/smart_datalake/test_code_cleaning.py
Labels: size:XL

#1256 [PAN-856]: Logs page added
  client/Providers/AppProvider.tsx
  client/app/(ee)/settings/layout.tsx
  client/app/(ee)/settings/logs/[id]/RenderDataFrame.tsx
  client/app/(ee)/settings/logs/[id]/loading.tsx
  client/app/(ee)/settings/logs/[id]/page.tsx
  client/app/(ee)/settings/logs/loading.tsx
  client/app/(ee)/settings/logs/logs-card.tsx
  client/app/(ee)/settings/logs/logs-interface.ts
  client/app/(ee)/settings/logs/page.tsx
  client/app/settings/datasets/AddNewCard.tsx
  client/app/settings/datasets/[id]/DatasetCard.tsx
  client/app/settings/datasets/[id]/loading.tsx
  client/app/settings/datasets/[id]/page.tsx
  client/app/settings/datasets/add/page.tsx
  client/app/settings/datasets/loading.tsx
  client/app/settings/datasets/page.tsx
  client/app/settings/layout.tsx
  client/components/ExecutionDetails/index.tsx
  client/components/LogsTable/index.tsx
  client/components/SettingsLayout/LeftBar.tsx
  client/components/codeHighlight/codeHighlight.tsx
  client/components/pagination/index.tsx
  client/hooks/useLogs.tsx
  client/lib/actions.ts
  client/package.json
  client/services/datasets.ts
  client/services/logs.ts
  client/utils/base64.ts
  client/utils/formatDate.ts
  client/yarn.lock
  server/api/v1/__init__.py
  server/app/controllers/chat.py
  server/app/models/__init__.py
  server/core/factory/factory.py
  server/core/server.py
  server/ee/api/__init__.py
  server/ee/api/v1/__init__.py
  server/ee/api/v1/logs/__init__.py
  server/ee/api/v1/logs/logs.py
  server/ee/app/__init__.py
  server/ee/app/controllers/__init__.py
  server/ee/app/controllers/logs.py
  server/ee/app/repositories/__init__.py
  server/ee/app/repositories/logs.py
  server/ee/app/schemas/__init__.py
  server/ee/app/schemas/responses/__init__.py
  server/ee/app/schemas/responses/logs.py
  server/migrations/README
  server/migrations/script.py.mako
  server/migrations/versions/20240603142118_initial_migration.py
  server/migrations/versions/20240626193035_init.py
  server/poetry.lock
  server/pyproject.toml
Labels: size:XXL

#1279 [PAN-868]: workspaces added
  client/app/settings/datasets/AddNewCard.tsx
  client/app/settings/datasets/page.tsx
  client/app/settings/workspaces/[id]/WorkspaceCard.tsx
  client/app/settings/workspaces/[id]/page.tsx
  client/app/settings/workspaces/addspaces/AddSpaceCard.tsx
  client/app/settings/workspaces/addspaces/loading.tsx
  client/app/settings/workspaces/addspaces/page.tsx
  client/app/settings/workspaces/editspaces/EditSpaceCard.tsx
  client/app/settings/workspaces/editspaces/loading.tsx
  client/app/settings/workspaces/editspaces/page.tsx
  client/app/settings/workspaces/loading.tsx
  client/app/settings/workspaces/page.tsx
  client/app/settings/workspaces/space-interface.ts
  client/components/SettingsLayout/LeftBar.tsx
  client/hooks/useSpaces.tsx
  client/lib/actions.ts
  client/services/spaces.ts
  server/api/v1/workspace/workspace.py
  server/app/controllers/workspace.py
  server/app/repositories/workspace.py
  server/app/schemas/requests/workspace.py
Labels: size:XL

#1285 import path fixed
  client/Providers/AppProvider.tsx
  client/components/LogsTable/index.tsx
Labels: size:S

#1286 DOC: Few typos fixed
  docs/library.mdx
  docs/platform.mdx
Labels: size:XS
