Repository sinaptik-ai/pandas-ai, pull requests merged in 2024-12, with the labels that each got.

#1443 feat(Dataframe): save dataframe yml
  pandasai/__init__.py
  pandasai/dataframe/base.py
  pandasai/helpers/utils.py
Labels: size:L

#1445 feat(push): dataframe push to the remote server
  pandasai/__init__.py
  pandasai/data_loader/loader.py
  pandasai/dataframe/base.py
  pandasai/helpers/request.py
Labels: size:L

#1446 feat(Dataframe): pull method to fetch dataset from remote server
  pandasai/__init__.py
  pandasai/data_loader/loader.py
  pandasai/dataframe/base.py
  pandasai/exceptions.py
  pandasai/helpers/request.py
  pandasai/vectorstores/bamboo_vectorstore.py
Labels: size:L

#1463 remove[BambooVectorstore]: delete bamboo vectorstore completely
  pandasai/agent/base.py
  pandasai/vectorstores/__init__.py
  pandasai/vectorstores/bamboo_vectorstore.py
  tests/unit_tests/vectorstores/test_bamboo_vector_store.py
Labels: size:L

#1467 feat(Unified_config): keep global config and use throughout the appli…
  pandasai/__init__.py
  pandasai/agent/base.py
  pandasai/agent/state.py
  pandasai/config.py
  pandasai/smart_dataframe/__init__.py
  pandasai/smart_datalake/__init__.py
Labels: size:XL

#1468 fix typo in smart_dataframe breaking import
  pandasai/smart_dataframe/__init__.py
Labels: size:XS, lgtm

#1474 fix(load): issue load path of dataset and virtualized=true error on csv
  pandasai/__init__.py
  pandasai/chat/code_execution/environment.py
  pandasai/data_loader/loader.py
  pandasai/data_loader/query_builder.py
Labels: size:M

#1484 Update last_code_generated in smart_dataframe's __init__.py
  pandasai/smart_dataframe/__init__.py
Labels: size:XS

#1486 Fix: docker-compose-npm-error
  client/components/card/index.tsx
Labels: size:XS

#1490 chore(PandaAIKey): improve set up for api key
  pandasai/__init__.py
  pandasai/config.py
Labels: size:S
