Repository sinaptik-ai/pandas-ai, pull requests merged in 2024-06, with the labels that each got.

#1194 chore: chainlit example using_chanlit.py
  examples/using_chainlit.py
Labels: size:M

#1196 feat(conversation_messages): return conversation messages
  server/api/v1/conversations/conversations.py
  server/app/controllers/conversation.py
  server/app/repositories/conversation.py
  server/app/schemas/responses/conversation.py
Labels: size:M, lgtm

#1197 [PAN-801]: datasets endpoint added
  server/api/v1/__init__.py
  server/api/v1/datasets/__init__.py
  server/api/v1/datasets/datasets.py
  server/app/controllers/datasets.py
  server/core/factory/factory.py
Labels: size:M

#1198 Fix/docker compose errors
  docker-compose.yml
  server/Dockerfile
  server/startup.sh
  server/wait-for-it.sh
Labels: size:M

#1199 fix: response message for strings and numbers
  server/core/utils/response_parser.py
Labels: size:XS

#1200 [PAN-816]: Past conversations integrated and workspace removed
  client/app/admin/conversations/[id]/messages/page.tsx
  client/app/page.tsx
  client/app/workspace/page.tsx
  client/components/ChatScreen/ChatInput.tsx
  client/components/LayoutComponents/ConversationItem.tsx
  client/services/conversations.ts
Labels: size:L

#1204 fix: JSON not serializable fix in using_chainlit.py
  examples/using_chainlit.py
Labels: size:M

#1205 [PAN-802]: Get workspace user endpoint added
  server/api/v1/__init__.py
  server/api/v1/datasets/datasets.py
  server/api/v1/workspace/__init__.py
  server/api/v1/workspace/workspace.py
  server/app/controllers/workspace.py
  server/app/repositories/workspace.py
  server/app/schemas/responses/users.py
  server/core/repository/base.py
Labels: size:M, lgtm

#1208 feat(train): semantic agent train method and multiturn conversation
  pandasai/agent/base.py
  pandasai/ee/agents/semantic_agent/__init__.py
  pandasai/ee/agents/semantic_agent/pipeline/llm_call.py
  pandasai/ee/agents/semantic_agent/pipeline/semantic_chat_pipeline.py
  pandasai/ee/agents/semantic_agent/pipeline/semantic_result_parsing.py
  pandasai/ee/agents/semantic_agent/prompts/templates/semantic_agent_prompt.tmpl
  pandasai/ee/agents/semantic_agent/prompts/templates/shared/vectordb_docs.tmpl
  pandasai/exceptions.py
  tests/unit_tests/ee/semantic_agent/test_semantic_agent.py
  tests/unit_tests/ee/semantic_agent/test_semantic_semantic_prompt_gen.py
Labels: size:L

#1209 [PAN-820]: archive conversation api added
  server/api/v1/conversations/conversations.py
  server/app/controllers/conversation.py
  server/app/controllers/workspace.py
Labels: size:M

#1207 [PAN-801]: Workspace datasets endpoint added
  server/api/v1/datasets/datasets.py
  server/api/v1/workspace/workspace.py
  server/app/controllers/datasets.py
  server/app/controllers/workspace.py
  server/app/repositories/dataset.py
  server/app/schemas/responses/datasets.py
  server/core/factory/factory.py
Labels: size:L, lgtm

#1210 [PAN-820]: archive api integrated on frontend
  client/Providers/AppProvider.tsx
  client/components/LayoutComponents/ConversationItem.tsx
  client/hooks/useConversations.tsx
  client/services/chat.ts
  client/services/conversations.ts
Labels: size:L, lgtm

#1212 docs: llms.mdx had outdated info about bambooLLM api key
  docs/llms.mdx
Labels: size:XS

#1215 [PAN-824]: Ui stuck fixed
  docker-compose.yml
  server/Dockerfile
  server/startup.sh
Labels: size:S

#1213 [PAN-828]: past conversation issues fixed
  client/app/admin/chat/page.tsx
  client/app/admin/conversations/[id]/messages/page.tsx
  client/components/ChatScreen/index.tsx
  client/services/chat.ts
  client/services/conversations.ts
  client/styles/globals.css
  server/app/controllers/conversation.py
Labels: size:L, lgtm

#1217 [PAN-828]: scroll to bottom from start fixed
  client/app/admin/conversations/[id]/messages/page.tsx
Labels: size:XS

#1216 tests(PandasAI-Server): adding pandasai server tests
  server/Makefile
  server/app/controllers/__init__.py
  server/app/repositories/__init__.py
  server/app/repositories/user.py
  server/core/controller/base.py
  server/core/repository/base.py
  server/poetry.lock
  server/pyproject.toml
  server/tests/app/repository/test_user_repository.py
  server/tests/core/app/controller/test_base_controller.py
  server/tests/core/database/test_transactional.py
  server/tests/core/factory/test_factory.py
  server/tests/core/respository/test_base_repository.py
  server/tests/core/utils/test_json_encoder.py
Labels: size:XL

#1218 [PAN-825]: new conversation not adding to sidebar fixed
  client/app/admin/chat/page.tsx
  server/app/controllers/chat.py
  server/app/repositories/conversation.py
  server/app/schemas/responses/chat.py
Labels: size:S

#1219 fix: frontend docker build
  docker-compose.yml
Labels: size:XS

#1230 Chore(SemanticAgent): improve time based aggregation and filtering
  pandasai/connectors/pandas.py
  pandasai/connectors/sql.py
  pandasai/ee/agents/semantic_agent/__init__.py
  pandasai/ee/agents/semantic_agent/pipeline/code_generator.py
  pandasai/ee/agents/semantic_agent/pipeline/error_correction_pipeline/error_correction_pipeline.py
  pandasai/ee/agents/semantic_agent/pipeline/error_correction_pipeline/error_prompt_generation.py
  pandasai/ee/agents/semantic_agent/pipeline/error_correction_pipeline/fix_semantic_json_pipeline.py
  pandasai/ee/agents/semantic_agent/pipeline/error_correction_pipeline/fix_semantic_schema_prompt.py
  pandasai/ee/agents/semantic_agent/pipeline/semantic_chat_pipeline.py
  pandasai/ee/agents/semantic_agent/prompts/fix_semantic_json.py
  pandasai/ee/agents/semantic_agent/prompts/templates/fix_semantic_json_prompt.tmpl
  pandasai/ee/helpers/query_builder.py
  pandasai/exceptions.py
  poetry.lock
  pyproject.toml
  tests/unit_tests/ee/helpers/schema.py
  tests/unit_tests/ee/semantic_agent/test__semantic_code_generator.py
  tests/unit_tests/ee/semantic_agent/test_semantic_agent.py
Labels: size:XXL

#1229 [PAN-822]: sidebar status persisted
  client/.eslintrc.json
  client/Providers/AppProvider.tsx
  client/components/AddUserModal/index.tsx
  client/components/AppTooltip/index.tsx
  client/components/ChatScreen/AIChatBubble.tsx
  client/components/ChatScreen/ChatDataFrame.tsx
  client/components/Icons/DownloadIcon.tsx
  client/components/Icons/SearchIcon.tsx
  client/components/LayoutComponents/ConversationItem.tsx
  client/components/LayoutComponents/LeftBar.tsx
  client/components/ui/tooltip.tsx
  client/package.json
  client/services/chat.ts
  client/styles/App.css
  client/styles/globals.css
  client/utils/convertToCSV.ts
Labels: size:L

#1239 fix(SemanticAgent): join data to be fixed
  pandasai/ee/helpers/query_builder.py
  tests/unit_tests/ee/helpers/schema.py
  tests/unit_tests/ee/helpers/test_query_builder.py
Labels: size:M

#1244 Add pandasai version in query tracker
  pandasai/helpers/query_exec_tracker.py
Labels: size:XS

#1245 adding Sonnet 3.5 and Opus to BedrockClaude's supported models
  pandasai/llm/bedrock_claude.py
Labels: size:XS

#1247 Fix/adding sonnet 3.5 to bedrock
  pandasai/llm/bedrock_claude.py
Labels: size:XS

#1246 [PAN-847]: datasets page added
  client/app/settings/datasets/[id]/DatasetCard.tsx
  client/app/settings/datasets/[id]/page.tsx
  client/app/settings/datasets/add/page.tsx
  client/app/settings/datasets/datasets-interface.ts
  client/app/settings/datasets/page.tsx
  client/app/settings/layout.tsx
  client/app/settings/page.tsx
  client/components/AddFormsDataSets/CsvDataSets.tsx
  client/components/Buttons/Button.tsx
  client/components/CardConnector/index.tsx
  client/components/Icons/AddWorkSpaceLarge.tsx
  client/components/Icons/UploadIcon.tsx
  client/components/SettingsLayout/LeftBar.tsx
  client/components/SettingsMenu/index.tsx
  client/components/Skeletons/index.tsx
  client/components/card/index.tsx
  client/components/ui/textarea.tsx
  client/hooks/useDatasets.tsx
  client/services/datasets.ts
  client/utils/apiUtils.ts
  server/api/v1/__init__.py
  server/api/v1/datasets/datasets.py
  server/app/controllers/datasets.py
  server/app/repositories/dataset.py
  server/app/repositories/workspace.py
  server/app/schemas/requests/datasets.py
  server/app/schemas/responses/datasets.py
Labels: size:XXL, lgtm
