Repository sinaptik-ai/pandas-ai, pull requests merged in 2024-10, with the labels that each got.

#1364 Fix Azure OpenAI LLM backend
  pandasai/llm/azure_openai.py
Labels: size:XS

#1350 docs: add AWS Bedrock tutorial to the example
  examples/with_aws.py
Labels: size:M

#1388 Removed _core property on SmartDataframe that causes maximum recursion depth exceeded
  pandasai/smart_dataframe/__init__.py
Labels: size:XS

#1381 Fix server Dockerfile
  server/Dockerfile
Labels: size:XS

#1366 Update custom-whitelisted-dependencies.mdx
  docs/custom-whitelisted-dependencies.mdx
Labels: size:XS

#1341 fix bug in malicious code scan
  pandasai/pipelines/chat/code_cleaning.py
Labels: size:XS

#1317 Fix/support chinese in prompt generation
  pandasai/helpers/dataframe_serializer.py
  tests/unit_tests/helpers/test_dataframe_serializer.py
Labels: size:M, lgtm

#1399 Fixed duplicate export dynamics when building client app
  client/app/(ee)/settings/logs/page.tsx
  client/app/settings/datasets/[id]/page.tsx
  client/app/settings/datasets/page.tsx
  client/app/settings/page.tsx
  client/app/settings/workspaces/addspaces/page.tsx
  client/app/settings/workspaces/editspaces/page.tsx
  client/app/settings/workspaces/page.tsx
Labels: size:L

#1410 Update llms.mdx
  docs/llms.mdx
Labels: size:S
