Repository sinaptik-ai/pandas-ai, pull requests merged in 2024-08, with the labels that each got.

#1311 update documentation
  docs/advanced-security-agent.mdx
  docs/cache.mdx
  docs/connectors.mdx
  docs/contributing.mdx
  docs/custom-head.mdx
  docs/custom-response.mdx
  docs/custom-whitelisted-dependencies.mdx
  docs/determinism.mdx
  docs/examples.mdx
  docs/favicon.svg
  docs/fields-description.mdx
  docs/intro.mdx
  docs/judge-agent.mdx
  docs/library.mdx
  docs/license.mdx
  docs/llms.mdx
  docs/mint.json
  docs/pipelines/pipelines.mdx
  docs/platform.mdx
  docs/semantic-agent.mdx
  docs/skills.mdx
  docs/train.mdx
Labels: size:XXL

#1319 LanceDB Integration
  docs/train.mdx
  pandasai/ee/vectorstores/__init__.py
  pandasai/ee/vectorstores/lanceDB.py
  poetry.lock
  pyproject.toml
  tests/unit_tests/vectorstores/test_lancedb.py
Labels: size:XL

#1295 fix: skill name is not defined
  pandasai/pipelines/chat/code_cleaning.py
  tests/unit_tests/pipelines/smart_datalake/test_code_cleaning.py
Labels: size:S, lgtm

#1346 fix(spellCheck): allow keyword for this case
  ignore-words.txt
  pandasai/ee/vectorstores/lanceDB.py
  tests/unit_tests/vectorstores/test_lancedb.py
Labels: size:M
