Repository sinaptik-ai/pandas-ai, pull requests merged in 2025-01, with the labels that each got.

#1500 fix: make seaborn as an optional dependency
  pandasai/helpers/dataframe_serializer.py
  pandasai/helpers/optional.py
Labels: size:XS

#1499 fix: check if whitelisted lib is actually exists in the additional deps
  pandasai/pipelines/chat/code_cleaning.py
  tests/unit_tests/pipelines/smart_datalake/test_code_cleaning.py
Labels: size:M

#1498 feat(security): add security config to disable it
  docs/library.mdx
  pandasai/agent/base.py
  pandasai/helpers/optional.py
  pandasai/pipelines/chat/code_cleaning.py
  pandasai/pipelines/chat/code_execution.py
  pandasai/safe_libs/base_restricted_module.py
  pandasai/schemas/df_config.py
  tests/unit_tests/agent/test_agent.py
  tests/unit_tests/helpers/test_optional_dependency.py
  tests/unit_tests/pipelines/smart_datalake/test_code_cleaning.py
Labels: size:L

#1502 fix(dataframe): default config for dataframe
  pandasai/dataframe/base.py
Labels: size:XS

#1507 feat(dataset): prompt message to the user on push and pull
  pandasai/dataframe/base.py
Labels: size:XS

#1504 fix(pandasai.json): remove llm configs from pandasi json file
  docs/library.mdx
  docs/llms.mdx
  pandasai.json
  pandasai/config.py
  pandasai/llm/__init__.py
Labels: size:M

#1508 fix(CI_Pipeline): resolve dependency issues causing build failures
  .github/workflows/ci-core.yml
  .github/workflows/ci-extensions.yml
  examples/from_csv.py
  extensions/ee/connectors/bigquery/poetry.lock
  extensions/ee/connectors/bigquery/pyproject.toml
  pandasai/__init__.py
  pandasai/config.py
  pandasai/helpers/request.py
  tests/unit_tests/helpers/test_dataframe_serializer.py
Labels: size:L

#1509 fix(prompt_id): attribute missing error
  pandasai/core/code_generation/code_cleaning.py
  pandasai/core/response/__init__.py
  pandasai/core/response/base.py
  pandasai/core/response/chart.py
  pandasai/core/response/dataframe.py
  pandasai/core/response/parser.py
  pandasai/dataframe/base.py
  tests/unit_tests/core/code_generation/test_code_cleaning.py
  tests/unit_tests/helpers/test_responses.py
  tests/unit_tests/response/test_chart_response.py
  tests/unit_tests/response/test_dataframe_response.py
Labels: size:L

#1510 fix(dataset): push dataset with name
  pandasai/dataframe/base.py
Labels: size:XS

#1511 refactor: update environment variable from PANDASAI_API_KEY to PANDABI_API_KEY and from PANDASAI_API_URL to PANDABI_API_URL
  README.md
  docs/v3/agent.mdx
  docs/v3/getting-started.mdx
  docs/v3/large-language-models.mdx
  examples/agent.py
  examples/dataframe.py
  examples/from_databricks.py
  examples/from_dataframe.py
  examples/from_excel.py
  examples/from_googlebigquery.py
  examples/from_parquet.py
  examples/from_snowflake.py
  examples/from_sql.py
  examples/from_yahoo_finance.py
  examples/save_chart.py
  examples/show_chart.py
  examples/sql_direct_config.py
  examples/using_train.py
  examples/using_workspace_env.py
  examples/with_multiple_dataframes.py
  examples/with_name_and_description.py
  pandasai/__init__.py
  pandasai/agent/base.py
  pandasai/config.py
  pandasai/constants.py
  pandasai/core/response/__init__.py
  pandasai/dataframe/base.py
  pandasai/helpers/request.py
  tests/unit_tests/agent/test_agent.py
  tests/unit_tests/dataframe/test_dataframe.py
  tests/unit_tests/prompts/test_generate_python_code_prompt.py
  tests/unit_tests/prompts/test_sql_prompt.py
  tests/unit_tests/test_pandasai_init.py
Labels: size:L

#1516 feat(SemanticLayerSchema): Adding a SemanticLayerSchema class with logical and business validation
  extensions/connectors/sql/tests/test_sql.py
  extensions/connectors/yfinance/tests/test_yahoo_finance.py
  extensions/ee/connectors/bigquery/pandasai_bigquery/__init__.py
  extensions/ee/connectors/bigquery/tests/test_bigquery.py
  extensions/ee/connectors/databricks/tests/test_databricks.py
  extensions/ee/connectors/oracle/pandasai_oracle/__init__.py
  extensions/ee/connectors/oracle/tests/test_oracle.py
  extensions/ee/connectors/snowflake/tests/test_snowflake.py
  extensions/ee/vectorstores/chromadb/tests/test_chromadb.py
  extensions/ee/vectorstores/pinecone/pandasai_pinecone/pinecone.py
  extensions/ee/vectorstores/qdrant/tests/test_qdrant.py
  extensions/llms/bedrock/pandasai_bedrock/__init__.py
  extensions/llms/bedrock/pandasai_bedrock/base.py
  extensions/llms/bedrock/tests/test_bedrock_claude.py
  extensions/llms/google/pandasai_google/__init__.py
  extensions/llms/google/pandasai_google/base.py
  extensions/llms/google/pandasai_google/google_gemini.py
  extensions/llms/google/pandasai_google/google_vertexai.py
  extensions/llms/google/tests/test_google_vertexai.py
  extensions/llms/huggingface/pandasai_huggingface/huggingface_text_gen.py
  extensions/llms/huggingface/tests/test_huggingface_text_gen.py
  extensions/llms/ibm/pandasai_ibm/ibm_watsonx.py
  extensions/llms/ibm/tests/test_ibm_watsonx.py
  extensions/llms/langchain/pandasai_langchain/langchain.py
  extensions/llms/langchain/tests/test_langchain_llm.py
  extensions/llms/local/pandasai_local/local_llm.py
  extensions/llms/local/tests/test_local_llm.py
  extensions/llms/openai/pandasai_openai/__init__.py
  extensions/llms/openai/pandasai_openai/azure_openai.py
  extensions/llms/openai/pandasai_openai/base.py
  extensions/llms/openai/pandasai_openai/openai.py
  extensions/llms/openai/tests/test_azure_openai.py
  extensions/llms/openai/tests/test_openai.py
  pandasai/constants.py
  pandasai/data_loader/semantic_layer_schema.py
  tests/unit_tests/dataframe/test_semantic_layer_schema.py
Labels: size:M

#1515 Added notebooks for 3.0 and removed old examples
  examples/agent.py
  examples/data/Loan payments data.parquet
  examples/data/Loan payments data.xlsx
  examples/data/heart.csv
  examples/data/loans_payments.csv
  examples/data/sample_dataframe.py
  examples/dataframe.py
  examples/from_csv.py
  examples/from_databricks.py
  examples/from_dataframe.py
  examples/from_excel.py
  examples/from_googlebigquery.py
  examples/from_parquet.py
  examples/from_snowflake.py
  examples/from_sql.py
  examples/from_yahoo_finance.py
  examples/load_dataset.py
  examples/quickstart.ipynb
  examples/save_chart.py
  examples/semantic_layer_csv.ipynb
  examples/show_chart.py
  examples/table_relations.py
  examples/use_openai_llm.ipynb
  examples/using_train.py
  examples/with_aws.py
  examples/with_azure.py
  examples/with_multiple_dataframes.py
  examples/with_name_and_description.py
  examples/with_vertexai.py
Labels: size:XXL

#1518 fix(pandasai_session): fix missing code and imports
  pandasai/helpers/session.py
Labels: size:XS

#1520 feat(SemanticLayerSchema): Refactoring using SemanticLayerSchema all over the code instead of the dictionary
  pandasai/data_loader/loader.py
  pandasai/data_loader/query_builder.py
  pandasai/data_loader/semantic_layer_schema.py
  pandasai/dataframe/base.py
  pandasai/dataframe/virtual_dataframe.py
  tests/unit_tests/dataframe/test_dataframe.py
  tests/unit_tests/dataframe/test_loader.py
  tests/unit_tests/dataframe/test_query_builder.py
  tests/unit_tests/dataframe/test_semantic_layer_schema.py
Labels: size:L

#1521 feat(SemanticLayerSchema): making column type optional and avoid dumping and parsing null values in the SemanticLayerSchema
  docs/v3/contributing.mdx
  docs/v3/semantic-layer.mdx
  pandasai/data_loader/loader.py
  pandasai/data_loader/semantic_layer_schema.py
  pandasai/dataframe/base.py
  tests/unit_tests/dataframe/test_dataframe.py
Labels: size:M

#1523 fix(Dataframe): adding default dataframe name to enable sql query on it, simplified dataframe serialization
  pandasai/__init__.py
  pandasai/core/prompts/templates/correct_execute_sql_query_usage_error_prompt.tmpl
  pandasai/core/prompts/templates/generate_python_code_with_sql.tmpl
  pandasai/core/prompts/templates/shared/dataframe.tmpl
  pandasai/dataframe/base.py
  pandasai/helpers/__init__.py
  pandasai/helpers/dataframe_serializer.py
  pandasai/helpers/sql_sanitizer.py
  tests/unit_tests/agent/test_agent.py
  tests/unit_tests/helpers/test_dataframe_serializer.py
  tests/unit_tests/helpers/test_sql_sanitizer.py
  tests/unit_tests/prompts/test_sql_prompt.py
Labels: size:L

#1527 fix(test): fixing tests for when PANDABI_API_KEY is present in .env
  pandasai/__init__.py
  pandasai/agent/base.py
  pandasai/agent/state.py
  pandasai/data_loader/schema_validator.py
  pandasai/dataframe/base.py
  tests/unit_tests/helpers/test_session.py
  tests/unit_tests/test_pandasai_init.py
Labels: size:M

#1528 fix(Agent): adding test to improve coverage
  pandasai/agent/base.py
  tests/unit_tests/agent/test_agent.py
  tests/unit_tests/dataframe/test_loader.py
Labels: size:M

#1526 docs: update v3 documentation, readme and examples
  README.md
  docs/mint.json
  docs/v3/agent.mdx
  docs/v3/ai-dashboards.mdx
  docs/v3/chat-and-cache.mdx
  docs/v3/chat-and-output.mdx
  docs/v3/conversational-agent.mdx
  docs/v3/data-ingestion.mdx
  docs/v3/data-layer.mdx
  docs/v3/dataframes.mdx
  docs/v3/getting-started.mdx
  docs/v3/introduction.mdx
  docs/v3/large-language-models.mdx
  docs/v3/overview-nl.mdx
  docs/v3/permission-management.mdx
  docs/v3/privacy-and-security.mdx
  docs/v3/semantic-layer.mdx
  docs/v3/share-dataframes.mdx
  docs/v3/smart-dataframes.mdx
  docs/v3/smart-datalakes.mdx
  examples/data_platform_guide.ipynb
  examples/quickstart.ipynb
  examples/semantic_layer_csv.ipynb
Labels: size:XL

#1539 fix: dependency issue and updated lock files
  .pre-commit-config.yaml
  extensions/connectors/sql/poetry.lock
  extensions/connectors/sql/pyproject.toml
  extensions/connectors/yfinance/poetry.lock
  extensions/connectors/yfinance/pyproject.toml
  extensions/ee/connectors/bigquery/poetry.lock
  extensions/ee/connectors/bigquery/pyproject.toml
  extensions/ee/connectors/databricks/poetry.lock
  extensions/ee/connectors/databricks/pyproject.toml
  extensions/ee/connectors/oracle/poetry.lock
  extensions/ee/connectors/oracle/pyproject.toml
  extensions/ee/connectors/snowflake/poetry.lock
  extensions/ee/connectors/snowflake/pyproject.toml
  extensions/ee/vectorstores/chromadb/poetry.lock
  extensions/ee/vectorstores/chromadb/pyproject.toml
  extensions/ee/vectorstores/lancedb/poetry.lock
  extensions/ee/vectorstores/lancedb/pyproject.toml
  extensions/ee/vectorstores/milvus/poetry.lock
  extensions/ee/vectorstores/milvus/pyproject.toml
  extensions/ee/vectorstores/pinecone/poetry.lock
  extensions/ee/vectorstores/pinecone/pyproject.toml
  extensions/ee/vectorstores/qdrant/poetry.lock
  extensions/ee/vectorstores/qdrant/pyproject.toml
  extensions/llms/bedrock/poetry.lock
  extensions/llms/bedrock/pyproject.toml
  extensions/llms/google/poetry.lock
  extensions/llms/google/pyproject.toml
  extensions/llms/huggingface/poetry.lock
  extensions/llms/huggingface/pyproject.toml
  extensions/llms/ibm/poetry.lock
  extensions/llms/ibm/pyproject.toml
  extensions/llms/langchain/poetry.lock
  extensions/llms/langchain/pyproject.toml
  extensions/llms/local/poetry.lock
  extensions/llms/local/pyproject.toml
  extensions/llms/openai/poetry.lock
  extensions/llms/openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#1537 feature(View): enabling view in loader
  pandasai/data_loader/loader.py
  pandasai/data_loader/query_builder.py
  pandasai/data_loader/semantic_layer_schema.py
  pandasai/data_loader/view_query_builder.py
  pandasai/dataframe/virtual_dataframe.py
  tests/unit_tests/dataframe/test_semantic_layer_schema.py
  tests/unit_tests/dataframe/test_view_query_builder.py
Labels: size:L

#1542 test: integration tests for error rate
  pandasai/data_loader/loader.py
  tests/unit_tests/agent/test_agent_chat.py
Labels: size:L

#1546 feature(LLMJudge): adding set of integration test where OpanAI is used as LLM Judge
  pandasai/__init__.py
  poetry.lock
  pyproject.toml
  tests/unit_tests/agent/test_agent_chat.py
  tests/unit_tests/agent/test_agent_llm_judge.py
  tests/unit_tests/conftest.py
Labels: size:L

#1548 fix: sanitize name of dataset in pai.load
  pandasai/data_loader/loader.py
  tests/unit_tests/dataframe/test_loader.py
Labels: size:S

#1543 feat(sql_connector): add support for sql connector
  docs/v3/semantic-layer.mdx
  extensions/connectors/sql/pandasai_sql/__init__.py
  extensions/connectors/sql/tests/test_sql.py
  pandasai/__init__.py
  pandasai/constants.py
  pandasai/data_loader/loader.py
  pandasai/data_loader/semantic_layer_schema.py
  pandasai/dataframe/base.py
  pandasai/dataframe/virtual_dataframe.py
  tests/unit_tests/dataframe/test_dataframe.py
  tests/unit_tests/dataframe/test_loader.py
  tests/unit_tests/test_pandasai_init.py
Labels: size:XL

#1550 docs: updated installation instructions and fixed semantic-layer parsing error
  README.md
  docs/v3/getting-started.mdx
  docs/v3/semantic-layer.mdx
Labels: size:S

#1549 feature(View): extend pai.create to support views
  pandasai/__init__.py
  pandasai/data_loader/semantic_layer_schema.py
  pandasai/helpers/path.py
  tests/unit_tests/test_pandasai_init.py
Labels: size:L

#1552 fix: removed deprecated df._data
  pandasai/data_loader/loader.py
  tests/unit_tests/agent/test_agent_llm_judge.py
  tests/unit_tests/prompts/test_sql_prompt.py
Labels: size:M

#1551 feat(sql_connector): add json serialization to text
  pandasai/core/response/base.py
  pandasai/core/response/chart.py
  pandasai/helpers/json_encoder.py
  tests/unit_tests/helpers/test_json_encoder.py
  tests/unit_tests/helpers/test_responses.py
Labels: size:L

#1517 feat(sandbox): adding docker sandbox
  docs/mint.json
  docs/v3/agent.mdx
  examples/docker_sandbox.ipynb
  extensions/sandbox/docker/README.md
  extensions/sandbox/docker/pandasai_docker/Dockerfile
  extensions/sandbox/docker/pandasai_docker/__init__.py
  extensions/sandbox/docker/pandasai_docker/docker_sandbox.py
  extensions/sandbox/docker/pandasai_docker/serializer.py
  extensions/sandbox/docker/poetry.lock
  extensions/sandbox/docker/pyproject.toml
  extensions/sandbox/docker/tests/test_sandbox.py
  extensions/sandbox/docker/tests/test_serializer.py
  pandasai/agent/base.py
  pandasai/core/code_execution/code_executor.py
  pandasai/sandbox/__init__.py
  pandasai/sandbox/sandbox.py
  tests/unit_tests/sandbox/test_sandbox.py
Labels: size:XXL
